### ISSUE TITLE
macOS Catalina and Mojave fails due to hardened rules

### ISSUE THREAD

**Issue by klmz** [zonkyio/embedded-postgres-binaries#21]
Since the last release, 9.6.17, i'm no longer able to use embedded-postgres. I get an IllegalStateException saying initDb failed:

````
27.03.2020 11:37:39.309 [main] WARN  o.s.w.c.s.GenericWebApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: 
org.springframework.beans.factory.BeanCreationException: 
Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: 
Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: 
Failed to instantiate [liquibase.integration.spring.SpringLiquibase]: 
Factory method 'liquibase' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: 
Error creating bean with name 'dataSource': 
FactoryBean threw exception on object creation; nested exception is com.google.common.util.concurrent.UncheckedExecutionException: 
java.lang.IllegalStateException: 
Process [/var/folders/3n/7mpl5l6j62v11xttxsjsk4wcfmyktc/T/embedded-pg/PG-5001232d5f8eb9a35a50839624b9a760/bin/initdb, -A, trust, -U, postgres, -D, /var/folders/3n/7mpl5l6j62v11xttxsjsk4wcfmyktc/T/epg17954755376373960693, -E, UTF-8] failed
````

Some more investigation reveals that initDb is indeed unable to run: 

````
❯ /var/folders/3n/7mpl5l6j62v11xttxsjsk4wcfmyktc/T/embedded-pg/PG-5001232d5f8eb9a35a50839624b9a760/bin/initdb -A trust -U postgres -D /var/folders/3n/7mpl5l6j62v11xttxsjsk4wcfmyktc/T/epg17954755376373960693 -E UTF-8
dyld: Library not loaded: @loader_path/../lib/libz.1.dylib
  Referenced from: /private/var/folders/3n/7mpl5l6j62v11xttxsjsk4wcfmyktc/T/embedded-pg/PG-5001232d5f8eb9a35a50839624b9a760/lib/libxml2.2.dylib
  Reason: no suitable image found.  Did find:
	file system relative paths not allowed in hardened programs
no data was returned by command ""/private/var/folders/3n/7mpl5l6j62v11xttxsjsk4wcfmyktc/T/embedded-pg/PG-5001232d5f8eb9a35a50839624b9a760/bin/postgres" -V"
The program "postgres" is needed by initdb but was not found in the
same directory as "/private/var/folders/3n/7mpl5l6j62v11xttxsjsk4wcfmyktc/T/embedded-pg/PG-5001232d5f8eb9a35a50839624b9a760/bin/initdb".
Check your installation.
````

It seems like this issue: #17 seems to cause this problem since going back to 9.6.16 fixes the issue.

I'm running on MacOS 10.15.2 and java 11: 
````
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
````

**Comment by tomix26** [comment]
Ok, thanks for the report, I'll take a look at it.

**Comment by tomix26** [comment]
Ok, I already know what is causing the problem.

The problem is in [EnterpriseDB binaries](https://www.enterprisedb.com/download-postgresql-binaries). Because the MacOS bundle contains exactly these binaries but only in reduced and repacked form. The previous binaries were not notarized and was running in legacy mode, so it was working fine. Whereas the new version of binaries are running in the [hardened runtime](https://developer.apple.com/documentation/security/hardened_runtime) which was introduced in macOS 10.14 Mojave. Apps running in the hardened runtime have some restrictons. One of them relates to using dynamically linked libraries. For using them must be enabled runtime exception to [allow DYLD environment variables](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_cs_allow-dyld-environment-variables) and maybe some other exceptions.

Unfortunately, at this moment the EnterpriseDB binaries do not have this exception enabled, so it does not work with the latest MacOS versions (Mojave and Catalina). We can only hope that people from EnterpriseDB will fix this issue and the next versions will be working again.

**Comment by chrisjenx** [comment]
Arg, so we can run these on OSx 😢

**Comment by chrisjenx** [comment]
Downgrading to 12.1 fixed this for me thankfully 😥

**Comment by tomix26** [comment]
@chrisjenx Thanks for the confirmation.

**Comment by phiros** [comment]
Any progress on this?

**Comment by chrisjenx** [comment]
I dropped embedded postgres db, we now run a local test db locally and our ci (GitHub Actions) runs a postgres server. Not only is this much much faster ~2s per test down to ~200ms (including dropping the pragma and recreating it for each test). It's a little closer to how your application would probably be talking db, we found some interesting connection closed issues by moving to a single instance which was masked by dropping and creating a new db on each test.

**Comment by tomix26** [comment]
@phiros Nope, the latest versions have the same problem.

**Comment by tomix26** [comment]
@chrisjenx Good for you. However, database cloning should not have such an impact on performance. Creating a new database on my machine takes only a few milliseconds.

**Comment by phiros** [comment]
BTW for people thinking they are affected by exactly this bug: 
Make sure you checked your **locale** settings as well! This does not seem important but it is (postgres is quite picky about some environment settings). See for more details: https://stackoverflow.com/questions/7165108/in-os-x-lion-lang-is-not-set-to-utf-8-how-to-fix-it/8161863#8161863

**Comment by chrisjenx** [comment]
> @chrisjenx Good for you. However, database cloning should not have such an impact on performance. Creating a new database on my machine takes only a few milliseconds, depending on the size of the database.

Yeah not sure, it would of thought so too, probably an osx issue? (My unix machine runs the same stack about 2-3x faster, so probably some crappy bottleneck in osx)

**Comment by gaddesai** [comment]
> BTW for people thinking they are affected by exactly this bug:
> Make sure you checked your **locale** settings as well! This does not seem important but it is (postgres is quite picky about some environment settings). See for more details: https://stackoverflow.com/questions/7165108/in-os-x-lion-lang-is-not-set-to-utf-8-how-to-fix-it/8161863#8161863

This fixed for me

**Comment by trecloux** [comment]
@tomix26 Do you think that the repackaging changes you applied in #30 might have fix this issue ?

**Comment by tomix26** [comment]
@trecloux Nope, still the same problem.

**Comment by tomix26** [comment]
I did some more digging and it seems that the primary problem was a missing libz library. I included the library into the bundle and now everything works fine.

**Comment by SButterfly** [comment]
Hi @tomix26
I reproduced the problem with  `dyld: Library not loaded: @loader_path/../lib/libz.1.dylib` in 12.2.0 version.
In what version did you fix it?

**Comment by tomix26** [comment]
The fixed versions were not officially released yet, I've released them right now. Since already published versions cannot be overridden in maven central repository, I had to release special versions with `-1` suffix. So fixed versions are `9.5.24-1`, `9.6.20-1`, `10.15.0-1`, `11.10.0-1`, `12.5.0-1`, `13.1.0-1`. See the [releases](https://github.com/zonkyio/embedded-postgres-binaries/releases) page for more information.

**Comment by smarvasti-bc** [comment]
All versions of zonky embedded postgres still fail for me. MacOS 12.2 M1 Pro

**Comment by thedevd** [comment]
For me ru.yandex.qatools.embed.postgresql started failing after I upgraded Mac os from 11 to 12.

**Comment by kovacshuni** [comment]
Still a problem. I'm using [testcontainers-scala](https://github.com/testcontainers/testcontainers-scala) instead (for some [testcontainers-java](https://github.com/testcontainers/testcontainers-java) may be more helpful). Maybe it's even better like this. Still the problem exists.

**Comment by ssoleimanii** [comment]
Same problem here with MacOS Monetary (12.3.1) M1!

**Comment by tainguyen210** [comment]
Same problem here with MacOS Monterey (12.3) M1

**Comment by quintencls** [comment]
Same problem here with MacOS 12.5 on a MacBook Pro 16-inch 2019

**Comment by quintencls** [comment]
FYI Upgrading to the 2.1.1 is working for me:

```
testImplementation('io.zonky.test:embedded-database-spring-test:2.1.1')
testImplementation('io.zonky.test:embedded-postgres:2.0.0')
```

I was using 1.6.3 before:

`testImplementation('io.zonky.test:embedded-database-spring-test:1.6.3')`

Afterwards I just needed to set the provider and type for the embedded db:

```
@AutoConfigureEmbeddedDatabase(
        provider = AutoConfigureEmbeddedDatabase.DatabaseProvider.ZONKY,
        type = AutoConfigureEmbeddedDatabase.DatabaseType.POSTGRES
)
```
